Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('abcpharma/', include('abcpharma.urls', namespace='abcpharma')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

abcpharma/urls.py
from django.urls import path
from . import views

#path arranged alphabetically by name
app_name= 'abcpharma'
urlpatterns=[
    #path('api/data', views.get_data, name='api-data'),

    #TEST URL
    path('index', views.CustomerIndexView.as_view(), name="index_view"),
    path('dashboard', views.DashboardIndexView.as_view(), name="dashboard_view"),
    path('customer-registration', views.CustomerRegistrationView.as_view(), name="customer_registration_view"),
    path('medicine-registration', views.MedicineRegistrationView.as_view(), name="medicine_registration_view"),
    path('order',views.CustomerOrderView.as_view(), name="order_view"), 
]

abcpharma/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Person(models.Model):
        firstname = models.CharField(max_length = 50)
        middlename = models.CharField(max_length = 50)
        lastname = models.CharField(max_length = 50)
        address = models.CharField(max_length = 100)
        birthDate = models.DateField()
        birthPlace = models.CharField(max_length = 50)
        status = models.CharField(max_length = 10)
        gender = models.CharField(max_length = 10)
        spouseName = models.CharField(max_length = 50) 
        spouseOccupation = models.CharField(max_length = 20)
        children = models.IntegerField(default=0)
        motherName = models.CharField(max_length = 50)
        motherOccupation = models.CharField(max_length = 20)
        fatherName = models.CharField(max_length = 50)
        fatherOccupation = models.CharField(max_length = 20)
        height = models.FloatField()
        weight = models.FloatField()
        religion = models.CharField(max_length = 30)
        

        class Meta:
            db_table = "Person"

class Customer(Person):
    photo = models.FileField()
    dateRegistered = models.DateField(default = datetime.now())
    isDeleted = models.IntegerField(default=0)
    
    #option 1
    #medicines = models.ManyToManyField(Medicine)
    class Meta:
        db_table = "Customer"

class Medicine(models.Model):
    dateRegistered = models.DateField(default = datetime.now)
    SKU = models.AutoField(primary_key=True)
    category = models.CharField(max_length = 100)
    genericName = models.CharField(max_length = 100)
    commonBrand = models.CharField(max_length  = 100)
    manufacturedDate = models.DateField(default = datetime.now)
    expiryDate = models.DateField(default = datetime.now)
    size = models.IntegerField()
    howToUse = models.TextField()
    sideEffects = models.TextField()
    price = models.DecimalField(max_digits = 10, decimal_places=2)
    noOfItems = models.IntegerField()
    images = models.ImageField(upload_to='upload/')
    isDeleted = models.IntegerField(default=0)

    class Meta:
        db_table = "Medicine"

#option 2
class Order(models.Model):
  customer = models.ForeignKey(Customer, null = False, blank = False, on_delete = models.CASCADE, related_name = "Customer")
  medicine = models.ForeignKey(Medicine, null=False, blank = False, on_delete = models.CASCADE, related_name = "Medicine")
  orderedDate = models.DateField(default = datetime.now)
  quantity = models.IntegerField(default = 0)

  class Meta:
      db_table = "Order"

class Login(models.Model):
    username = models.IntegerField()
    
    class Meta:
        db_table = "currentUser"

abcpharma/forms.py
from django import forms
from .models import *

class CustomerForm(forms.ModelForm):

	class Meta:
		model = Customer
		fields = ('firstname','lastname','address','status','gender','motherName',
			'motherOccupation','fatherName','fatherOccupation','height','weight')
		
class MedicineForm(forms.ModelForm):
    
    class Meta:
        model = Medicine
        fields = ('category','genericName')

class OrderForm(forms.ModelForm):

	class Meta:
		model = Order
		fields = ('quantity',)

class LoginForm(forms.ModelForm):

	class Meta:
		model = Login
		fields = ('username',)

abcpharma/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.http import Http404
from django.http import HttpResponse
from .forms import *
from .models import *
from django.core.files.storage import default_storage

# Create your views here.

class CustomerIndexView(View):
    def get(self, request):
        return render(request, 'index.html')

    def post(self, request):
        user = request.POST.get("username")
        customers = Customer.objects.all()
        form = LoginForm(request.POST)

        for customer in customers:
            if str(customer.id) == user and customer.isDeleted != 1:                
                if form.is_valid():
                    username1 = request.POST.get("username")
                    form = Login.objects.get(id=1)
                    form.username = username1
                    form.save()   
                return redirect('abcpharma:order_view')

        return HttpResponse("Username does not exist.")
        
class CustomerRegistrationView(View):
    def get(self, request):
        return render(request, 'customerRegistration.html')

    def post(self,request):
        form = CustomerForm(request.POST)

        if form.is_valid():
            profilePic = request.FILES['profile_photo']
            fname = request.POST.get("firstname")
            mname = request.POST.get("middlename")
            lname = request.POST.get("lastname")
            address = request.POST.get("address")
            bday = request.POST.get("birthdate")
            bplace = request.POST.get("birthplace")
            status = request.POST.get("status")
            gender = request.POST.get("gender")
            spouseN = request.POST.get("spouseName")
            spouseO = request.POST.get("spouseOccupation")
            numChild = request.POST.get("numChildren")
            motherN = request.POST.get("motherName")
            motherO = request.POST.get("motherOccupation")
            fatherN = request.POST.get("fatherName")
            fatherO = request.POST.get("fatherOccupation")
            height = request.POST.get("height")
            weight = request.POST.get("weight")
            religion = request.POST.get("religion")
            dateReg = request.POST.get("dateRegistered")

            form = Customer(photo = profilePic, firstname = fname, middlename = mname, lastname = lname, address = address,
                birthDate = bday, birthPlace = bplace, status = status, gender = gender, spouseName = spouseN, 
                spouseOccupation = spouseO, children = numChild, motherName = motherN, motherOccupation = motherO,
                fatherName = fatherN, fatherOccupation = fatherO, height = height, weight = weight, religion = religion, 
                dateRegistered = dateReg)
            form.save()

            return redirect('abcpharma:dashboard_view')
        else:
            print(form.errors)
            return HttpResponse('not valid')

class CustomerOrderView(View):
    def get(self, request):
        medicines = Medicine.objects.filter(isDeleted = 0)
        currentUser = Login.objects.values_list("username", flat=True).get(pk = 1)
        orders = Order.objects.filter(customer_id = currentUser)
        
        customers = Customer.objects.filter(person_ptr_id = currentUser)
        context = {
            'medicines' : medicines,
            'customers' : customers,
            'orders' : orders
        }
        return render(request, 'orderPage.html', context)

    def post(self, request):
        form = OrderForm(request.POST)
        SKU = request.POST.get("SKU")
        orders = Order.objects.all()
        currentUser = Login.objects.values_list("username", flat=True).get(pk = 1)

        if request.method == 'POST':
            if 'btnBuy' in request.POST:
                number = request.POST.get("noOfItems")
                quantity = request.POST.get("quantity")
                dif = int(number) - int(quantity)
                if form.is_valid():
                    for order in orders:
                        if(int(order.medicine_id) == int(SKU) and int(order.customer_id) == int(currentUser)):
                            quantity1 = int(order.quantity) + int(quantity)                                             
                            update_quantity = Order.objects.filter(id = order.id).update(quantity = quantity1)
                            update_quantity = Medicine.objects.filter(SKU = SKU).update(noOfItems = dif)
                            return redirect('abcpharma:order_view')
                    
                    form = Order(medicine_id = SKU, customer_id = currentUser, quantity = quantity)
                    update_quantity = Medicine.objects.filter(SKU = SKU).update(noOfItems = dif)
                    form.save()                             
                return redirect('abcpharma:order_view')
                
                
                

                
                


class DashboardIndexView(View):
    def get(self, request):
        customers = Customer.objects.all()
        medicines = Medicine.objects.all()
        context = {
            'customers' : customers,
            'medicines' : medicines
        }
        return render(request, 'dashboard.html', context)
    
    def post(self, request):
        if request.method == 'POST':
            if 'btnUpdateMedicine' in request.POST:
                print('update profile button clicked')
                SKU1 = request.POST.get("SKU")
                category1 = request.POST.get("category")
                genericName1 = request.POST.get("genericName")
                commonBrand1 = request.POST.get("commonBrand")
                manufacturedDate1 = request.POST.get("manufacturedDate")
                expiryDate1 = request.POST.get("expiryDate")
                size1 = request.POST.get("size")
                howToUse1 = request.POST.get("howToUse")
                sideEffects1 = request.POST.get("sideEffects")
                price1 = request.POST.get("price")
                noOfItems1 = request.POST.get("noOfItems")
                print(manufacturedDate1)
                print(noOfItems1)
                print(SKU1)
                update_medicine = Medicine.objects.filter(SKU=SKU1).update(category = category1, genericName = genericName1, commonBrand = commonBrand1, manufacturedDate = manufacturedDate1, expiryDate = expiryDate1, size = size1,
                    howToUse = howToUse1, sideEffects = sideEffects1, price = price1, noOfItems = noOfItems1)
            elif 'btnDeleteMedicine' in request.POST:
                print('delete button clicked')
                SKU1 = request.POST.get("SKU")
                print(SKU1)
                med = Medicine.objects.filter(SKU = SKU1).update(isDeleted = 1)
                print('Deleted')
            elif 'btnUpdateCustomer' in request.POST:
                customerID = request.POST.get("customer-id")
                fname = request.POST.get("customer-firstname")
                mname = request.POST.get("customer-middlename")
                lname = request.POST.get("customer-lastname")
                address = request.POST.get("customer-address")
                bday = request.POST.get("customer-birthdate")
                bplace = request.POST.get("customer-birthplace")
                status = request.POST.get("customer-status")
                gender = request.POST.get("customer-gender")
                spouseN = request.POST.get("customer-spousename")
                spouseO = request.POST.get("customer-spouseoccupation")
                numChild = request.POST.get("customer-children")
                motherN = request.POST.get("customer-mothername")
                motherO = request.POST.get("customer-motheroccupation")
                fatherN = request.POST.get("customer-fathername")
                fatherO = request.POST.get("customer-fatheroccupation")
                height = request.POST.get("customer-height")
                weight = request.POST.get("customer-weight")
                religion = request.POST.get("customer-religion")

                update_customer = Customer.objects.filter(person_ptr_id = customerID).update(firstname = fname, 
                    middlename = mname, lastname = lname, address = address, birthDate = bday, birthPlace = bplace, 
                    status = status, gender = gender, spouseName = spouseN, spouseOccupation = spouseO, children = numChild, 
                    motherName = motherN, motherOccupation = motherO, fatherName = fatherN,  fatherOccupation = fatherO, 
                    height = height, weight = weight, religion = religion)
                print(update_customer)
            elif 'btnDeleteCustomer' in request.POST:
                customerID = request.POST.get("customerr-id")
                customerr = Customer.objects.filter(person_ptr_id = customerID).update(isDeleted = 1)
                #personn = Person.objects.filter(id = customerID).delete()
                
        return redirect('abcpharma:dashboard_view')

class MedicineRegistrationView(View):
    def get(self, request):
       # print('get')
        return render(request, 'medReg.html')
    
    def post(self, request):
        form = MedicineForm(request.POST)
        if form.is_valid():
            category1 = request.POST.get("category")
            genericName1 = request.POST.get("genericName")
            commonBrand1 = request.POST.get("commonBrand")
            manufacturedDate1 = request.POST.get("manufacturedDate")
            expiryDate1 = request.POST.get("expiryDate")
            size1 = request.POST.get("size")
            howToUse1 = request.POST.get("howToUse")
            sideEffects1 = request.POST.get("sideEffects")
            price1 = request.POST.get("price")
            noOfItems1 = request.POST.get("noOfItems")
            images = request.FILES['images']
            
            

abcpharma/templates/customerRegistration.html
{% block headerinclude %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <style>
	    body {
	    	background-image: url('https://images.assetsdelivery.com/compings_v2/elenavdovina/elenavdovina1705/elenavdovina170500036.jpg');
			margin: 0;
			font-family: arial;
			font-style: normal;
		}

		h1 {
			text-align: center;
			line-height: 1.8;
		}

		.header {
	        background-color: black;
	        color: white;
	    }

		.form-container {
			background-color: white;
			margin: 2% auto;
			width: 50%;
			height: 297%;
			border: 3px solid black;
			padding: 10px;
		}

		form label[for=details] {
		  	font-weight: bold;
		}

		select {
			width: 100%;
			padding: 12px 20px;
			margin: 1px 0;
			display: inline-block;
			border: 1px solid #ccc;
			border-radius: 4px;
			box-sizing: border-box;
		}
			
		input[type=text], input[type=password], input[type=number] {
			width: 100%;
			padding: 12px 20px;
			margin: 1px 0;
			display: inline-block;
			border: 1px solid #ccc;
			border-radius: 4px;
			box-sizing: border-box;
		}

		input[type=date] {
			width: 100%;
			padding: 12px 20px;
			margin: 1px 0;
			display: inline-block;
			border: 1px solid #ccc;
			border-radius: 4px;
			box-sizing: border-box;
		}

		input[type=radio] {
			margin-left: 50px;
		}

		input:invalid {
		  box-shadow: 0 0 5px 1px red;
		}

		input:focus:invalid {
		  box-shadow: none;
		}

		a {
			text-align: center;
			padding: 12px 20px;
			margin: 8px 0;
			display: inline-block;
			border: 1px solid #ccc;
			border-radius: 4px;
			box-sizing: border-box;
		}

		.buttonCancel {
			width: 49%;
		  	color: white;
		  	padding: 12px 20px;
		  	margin: 14px 0px;
		  	border: none;
		  	border-radius: 4px;
		  	cursor: pointer;
		  	background-color: grey
		}

		.buttonCancel:hover {
			text-decoration: none;
			color: black;
		  	padding: 12px 20px;
		  	margin: 14px 0px;
		  	border: 1px solid black;
		  	border-radius: 4px;
		  	cursor: pointer;
		  	background-color: lightgrey;
		}

		.buttonRegister {
			width: 49%;
		  	color: white;
		  	padding: 12px 20px;
		  	margin: 14px 0px;
		  	border: none;
		  	border-radius: 4px;
		  	cursor: pointer;
		  	background-color: #4CAF50;
		}

		.buttonRegister:hover{
			background-color: white;
        	border: 1px solid #4CAF50;
        	text-decoration: none;
        	color: black;
        	width: 49%;
		  	border-radius: 4px;
		  	cursor: pointer;
		}

		.ft {
	      	text-align: center;
	      	padding: 8px;
	      	background-color: black;
	      	color: white;
	    }
	</style>
    <title>Customer Registration</title>
{% endblock headerinclude %}


{% block footerinclude %}
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock footerinclude %}


{% block content %}
	<div class="header"><h1> ABC Pharma Automate</h1></div>
	<div class="form-container">
		<h1><b>CUSTOMER REGISTRATION</b></h1>

		<form id="form1" action="" method="POST" autocomplete="off" enctype="multipart/form-data">
			{% csrf_token %}
			<center>
				<label for="details">Profile Picture</label><br>
				<img id="preview" width="150px" height="150px" style="box-shadow: 0 0 5px 1px black;"><br><br>
				<input type="file" id="id-profilepicture" name="profile_photo" accept=".png, .jpg, .jpeg" onchange="load_image(this.id, this.value)" required><br><br>
			</center>

			<script type="text/javascript">
				function load_image(id,ext)
				{
				   if(validateExtension(ext) == false)
				   {
				      alert("Upload only JPEG/JPG or PNG format ");
				      document.getElementById("preview").innerHTML = "";
				      document.getElementById('id-profilepicture').value = null;
				      return;
				   }
				}

			    function validateExtension(v)
				{
				      var allowedExtensions = new Array("jpg","JPG","jpeg","JPEG", "png", "PNG");
				      for(var ct=0;ct<allowedExtensions.length;ct++)
				      {
				          sample = v.lastIndexOf(allowedExtensions[ct]);
				          if(sample != -1){return true;}
				      }
				      return false;
				}

				var input = document.querySelector('#id-profilepicture');
				input.addEventListener('change', preview);
				function preview(){
					var fileObject = this.files[0];
					var fileReader = new FileReader();
					fileReader.readAsDataURL(fileObject);
					fileReader.onload = function(){
						var result = fileReader.result;
						var img = document.querySelector('#preview');
						img.setAttribute('src', result);
					}
				}
			</script>

			<div class="row">
				<div class="col-sm-6">
					<label for="details">Date Registered</label>
					<input type="date" id="id-dateRegistered" name="dateRegistered">
				</div>
				<div class="col-sm-6">
					<label for="details">Customer ID</label>
					<input disabled type="number" id="id-customerID" name="customerID" placeholder="Auto-generated">
				</div>
			</div><br>

			<script>
				$(document).ready(function() {
				    var date = new Date();

				    var day = date.getDate();
				    var month = date.getMonth() + 1;
				    var year = date.getFullYear();

				    if (month < 10) month = "0" + month;
				    if (day < 10) day = "0" + day;

				    var today = year + "-" + month + "-" + day;       
				    $("#id-dateRegistered").attr("value", today);
				});
			</script>

			<div class="row">
				<div class="col-sm-4">
					<label for="details">First Name</label>
				</div>
				<div class="col-sm-4">
					<label for="details">Middle Name</label>
				</div>
				<div class="col-sm-4">
					<label for="details">Last Name</label>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-4">
					<input type="text" id="-id-firstname" name="firstname" placeholder="First Name" maxlength="50" required>
				</div>
				<div class="col-sm-4">
					<input type="text" id="id-middlename" name="middlename" placeholder="Middle Name" maxlength="50">
				</div>
				<div class="col-sm-4">
					<input type="text" id="id-lastname" name="lastname" placeholder="Last Name" maxlength="50" required>
				</div>
			</div><br>

			<label for="details">Address</label>
			<input type="text" id="id-address" name="address" placeholder="Street, Brgy, City, Prov, Zip, Country" maxlength="100" required><br><br>

			<label for="details">Birthdate</label>
			<input type="date" id="id-birthdate" name="birthdate" required><br><br>

			<label for="details">Birthplace</label>
			<input type="text" id="id-birthplace" name="birthplace" placeholder="Birthplace" maxlength="50" required><br><br>

			<label for="details">Status</label><br>
			<input type="radio" id="Single" name="status" value="Single" required>Single
			<input type="radio" id="Married" name="status" value="Married" required>Married
			<input type="radio" id="Widow/er" name="status" value="Widow/er" required>Widow/er
			<input type="radio" id="Divorced" name="status" value="Divorced" required>Divorced<br><br>

			<label for="details">Gender</label><br>
			<input type="radio" id="Male" name="gender" value="Male" required>Male
			<input type="radio" id="Female" name="gender" value="Female" required>Female<br><br>

			<label for="details">Spouse's name</label>
			<input type="text" id="id-spouseName" name="spouseName" maxlength="50"><br><br>

			<label for="details">Spouse occupation</label>
			<input type="text" id="id-spouseOccupation" name="spouseOccupation" maxlength="20"><br><br>

			<label for="details">No. of Children</label>
			<input type="number" id="id-numChildren" name="numChildren" value="0" min="0"><br><br>

			<label for="details">Mother's Name</label>
			<input type="text" id="id-motherName" name="motherName" maxlength="50" required><br><br>

			<label for="details">Mother's Occupation</label>
			<input type="text" id="id-motherOccupation" name="motherOccupation" maxlength="20" required><br><br>

			<label for="details">Father's Name</label>
			<input type="text" id="id-fatherName" name="fatherName" maxlength="50" required><br><br>

			<label for="details">Father's Occupation</label>
			<input type="text" id="id-fatherOccupation" name="fatherOccupation" maxlength="20" required><br><br>

			<label for="details">Height (cm)</label>
			<input type="number" step="any" id="id-height" name="height" min="20" required><br><br>

			<label for="details">Weight (kg)</label>
			<input type="number" step="any" id="id-weight" name="weight" min="20" required><br><br>

			<label for="details">Religion</label>
			<input type="text" id="id-religion" name="religion" maxlength="30" required><br>

			<a type="button" href="{% url 'abcpharma:index_view' %}" class="buttonCancel">Cancel</a>
			<button type="submit" class="buttonRegister">Register</button>
		</form>
	</div>
{% endblock content %}